"""
extract_interesting_plans.py
============================
Post-processing: scan plans_final.jsonl files (which were generated by an older
run_recom.py that lacked the interesting-plan saving logic) and extract the first
plan that matches each criterion, provided that plan's assignment was saved.

Usage:
    python analytics/extract_interesting_plans.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

JOBS = [
    {
        "label": "AL raceblind",
        "plans": (
            ROOT / "cse416_seawulf_results"
            / "AL_output_raceblind" / "plans_final.jsonl"
        ),
        "outdir": ROOT / "cse416_seawulf_results" / "AL_output_raceblind",
        "interesting_plans": [
            {
                "id": "zero_effective",
                "description": "Zero effective Black minority districts",
                "criteria": {"eff_districts": {"eq": 0}},
            },
        ],
    },
    {
        "label": "OR raceblind",
        "plans": (
            ROOT / "cse416_seawulf_results"
            / "OR_output_raceblind" / "plans_final.jsonl"
        ),
        "outdir": ROOT / "cse416_seawulf_results" / "OR_output_raceblind",
        "interesting_plans": [
            {
                "id": "high_effectiveness",
                "description": (
                    "Two or more effective Latino minority districts"
                ),
                "criteria": {"eff_districts": {"gte": 2}},
            },
            {
                "id": "zero_effective",
                "description": "Zero effective Latino minority districts",
                "criteria": {"eff_districts": {"eq": 0}},
            },
        ],
    },
]


def _matches_criterion(value, op_dict):
    if value is None:
        return False
    ops = {
        "eq":  lambda v, t: v == t,
        "gte": lambda v, t: v >= t,
        "gt":  lambda v, t: v > t,
        "lte": lambda v, t: v <= t,
        "lt":  lambda v, t: v < t,
    }
    for op, target in op_dict.items():
        if op not in ops or not ops[op](value, target):
            return False
    return True


def _plan_matches(rec, criteria):
    for field, spec in criteria.items():
        val = rec.get(field)
        if isinstance(spec, dict):
            if not _matches_criterion(val, spec):
                return False
        else:
            if val != spec:
                return False
    return True


def extract_job(job):
    plans_path = job["plans"]
    outdir = Path(job["outdir"])
    defs = job["interesting_plans"]
    label = job["label"]

    if not plans_path.exists():
        print(f"[{label}] SKIP — file not found: {plans_path}")
        return

    found = {d["id"]: False for d in defs}

    with plans_path.open(encoding="utf-8") as f:
        for raw in f:
            raw = raw.strip()
            if not raw:
                continue
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue

            if "assignment" not in rec:
                continue

            for plan_def in defs:
                pid = plan_def["id"]
                if found[pid]:
                    continue
                if not _plan_matches(rec, plan_def["criteria"]):
                    continue

                record = {
                    "plan_id": pid,
                    "description": plan_def["description"],
                    "step": rec.get("step"),
                    "metrics": {
                        k: rec[k]
                        for k in ("dem_seats", "rep_seats", "eff_districts",
                                  "opp_districts", "cut_edges")
                        if k in rec
                    },
                    "assignment": rec["assignment"],
                }
                out = outdir / f"interesting_plan_{pid}.json"
                out.write_text(json.dumps(record), encoding="utf-8")
                print(f"[{label}] Saved '{pid}' (step {rec.get('step')}) → {out}")
                found[pid] = True

            if all(found.values()):
                break

    for plan_def in defs:
        if not found[plan_def["id"]]:
            print(
                f"[{label}] WARNING: '{plan_def['id']}'"
                " not found (no saved-assignment plan matched)."
            )


def main():
    for job in JOBS:
        extract_job(job)
    print("Done.")


if __name__ == "__main__":
    main()
