package edu.stonybrook.cse416.backend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * PlanDoc — MongoDB document model for the {@code plans} collection.
 *
 * <p>A plan is a single redistricting map generated by the ReCom Markov chain
 * within a parent ensemble. Each plan stores a list of district assignments —
 * one integer per precinct node — that maps every precinct to a congressional
 * district number. The order of the {@code assignments} list corresponds to
 * the node order in the precinct adjacency graph.
 *
 * <p>Mapped to the {@code plans} collection via
 * {@link Document @Document(collection = "plans")}.
 */
@Document(collection = "plans")
public class PlanDoc {

    /** MongoDB document ID — unique across all plans in all ensembles. */
    @Id
    private String id;

    /**
     * Reference to the parent {@link EnsembleDoc#getEnsembleId() ensembleId}.
     * Used to fetch all plans belonging to a given ensemble.
     */
    private String ensembleId;

    /**
     * Zero-based index of this plan within its ensemble.
     * Plans are indexed from 0 to {@code numPlans - 1}.
     */
    private Integer planIndex;

    /**
     * Ordered list of district assignments: {@code assignments.get(i)} is the
     * congressional district number (1-based) assigned to the i-th precinct
     * node in the precinct graph.
     */
    private List<Integer> assignments;

    /** No-arg constructor required by Spring Data MongoDB. */
    public PlanDoc() {}

    /**
     * Returns the MongoDB document ID for this plan.
     * @return document ID string.
     */
    public String getId() { return id; }

    /**
     * Sets the MongoDB document ID.
     * @param id document ID string.
     */
    public void setId(String id) { this.id = id; }

    /**
     * Returns the parent ensemble ID.
     * @return ensemble ID this plan belongs to.
     */
    public String getEnsembleId() { return ensembleId; }

    /**
     * Sets the parent ensemble ID.
     * @param ensembleId ensemble ID string.
     */
    public void setEnsembleId(String ensembleId) { this.ensembleId = ensembleId; }

    /**
     * Returns the zero-based index of this plan within its ensemble.
     * @return plan index.
     */
    public Integer getPlanIndex() { return planIndex; }

    /**
     * Sets the zero-based plan index.
     * @param planIndex plan index within the ensemble.
     */
    public void setPlanIndex(Integer planIndex) { this.planIndex = planIndex; }

    /**
     * Returns the ordered district assignment list.
     * Element {@code i} is the district number assigned to the i-th precinct node.
     * @return list of integer district assignments.
     */
    public List<Integer> getAssignments() { return assignments; }

    /**
     * Sets the district assignment list.
     * @param assignments ordered list of district numbers (one per precinct node).
     */
    public void setAssignments(List<Integer> assignments) { this.assignments = assignments; }
}
